#!/usr/bin/env bash
# Sequential paper-grade re-run of the 7 TSFM baselines under --seed 42.
# Generated by the paper-grade upgrade plan.
#
# - Chronos-2 runs in the `telco-chronos-test` conda env (chronos-forecasting==2.0.0).
# - 5 Moirai variants + MOMENT run in the `telcoagent` env.
# - Each sweep is 81 ctx × 115 stations; total wall time ~6–9h on one GPU.
#
# Logs to /tmp/repro_all_baselines.log. Safe to launch via:
#     nohup bash scripts/baselines/_rerun_all_paper_baselines.sh \
#         > /tmp/repro_all_baselines.log 2>&1 &
#     echo "PID=$!"

set -u

cd "$(git rev-parse --show-toplevel 2>/dev/null || pwd)"

log() { echo "[$(date '+%F %T')] $*"; }

PYBIN_TELCO="conda run -n telcoagent python"
PYBIN_CHRONOS="conda run -n telco-chronos-test python"

log "Starting paper-grade re-run (--seed 42)"

# 1) Chronos-2 (separate env required: chronos-forecasting==2.0.0)
log "=== [1/7] amazon/chronos-2 (telco-chronos-test env) ==="
$PYBIN_CHRONOS scripts/baselines/run_chronos2_context_sweep.py --seed 42

# 2) Moirai 1.1 small / base / large
for variant in moirai-1.1-R-small moirai-1.1-R-base moirai-1.1-R-large; do
    log "=== Salesforce/$variant (telcoagent env) ==="
    $PYBIN_TELCO scripts/baselines/run_moirai_family_context_sweep.py \
        --model "Salesforce/$variant" --seed 42
done

# 3) Moirai-MoE small / base
for variant in moirai-moe-1.0-R-small moirai-moe-1.0-R-base; do
    log "=== Salesforce/$variant (telcoagent env) ==="
    $PYBIN_TELCO scripts/baselines/run_moirai_family_context_sweep.py \
        --model "Salesforce/$variant" --seed 42
done

# 4) MOMENT
log "=== [7/7] AutonLab/MOMENT-1-large (telcoagent env) ==="
$PYBIN_TELCO scripts/baselines/run_moment_context_sweep.py --seed 42

log "All 7 baselines complete."
